language: python
python:
    - "2.7"
before_install:
    - deactivate
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-scipy python-nose python-cvxopt python-sklearn
    - virtualenv --system-site-packages ~/virtualenv/this
    - source ~/virtualenv/this/bin/activate
    - pip install cython --use-mirrors
    - pip install git+git://github.com/fgregg/pyqpbo.git#egg=pyqbo
    # Workaround for a permissions issue with Travis virtual machine images
    # that breaks Python's multiprocessing:
    # https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm 
install: python setup.py build_ext --inplace
script: make test
