language: python
python:
    - "2.7"
before_install:
    - deactivate
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-scipy python-nose python-cvxopt python-sklearn
    - virtualenv --system-site-packages ~/virtualenv/this
    - source ~/virtualenv/this/bin/activate
    - pip install -r requirements.txt --use-mirrors
install: python setup.py build_ext --inplace
script: make test
